### ISSUE TITLE
Previews for the site have no image

### ISSUE THREAD

**Issue by PsychoData** [adamfowlerit/msportals.xyz#25]
The preview for Discord is kind of redundant/annoying
![image](https://user-images.githubusercontent.com/3719116/97878808-1af4a680-1ced-11eb-87b9-f99710535309.png)

As best I can tell - the sources of these values are 
![image](https://user-images.githubusercontent.com/3719116/97880361-14ffc500-1cef-11eb-983f-7fd3ce7324f3.png)

We might want to look at separating out the "End User" Apps versus "Administrator" portals too, just because there are so many individual apps to deal with, and separating those off would make things much shorter to scroll

**Comment by PsychoData** [comment]
we could try to add some images to it? 

There is the Office/M365 icon, but I wouldn't want to get people confused with the "real" sites if they tried to go by favicon in the tab
<img src="https://user-images.githubusercontent.com/3719116/97881896-f8fd2300-1cf0-11eb-8573-8258b70a71c7.png" width="100" height="100">
or the O365 Admin Icon

<img src="https://user-images.githubusercontent.com/3719116/97882947-38783f00-1cf2-11eb-8e83-7d0fa8673a63.png" width="100" height="100">
from https://account.activedirectory.windowsazure.com/images/tiles/o365logos/shellAdmin.png
Might be better to get/make a version with a transparent background, though

Or possibly a NinjaCat? 
<img src="https://user-images.githubusercontent.com/3719116/97883175-83925200-1cf2-11eb-9d55-5801b92013ba.png" width="100" height="100">
from https://mspoweruser.com/here-are-a-bunch-of-windows-10-ninja-cat-wallpapers/

 What do  you all think? or other ideas? 
For what it is worth, some of these logos are probably copyrighted or trademarked or something, but as long as we aren't making money off it, we might be fine using them. At least until we get contacted to tell us to stop using them

**Comment by adamfowlerit** [comment]
Agree on the preview problem. I like the O365 Admin icon, till we can get something better. Also, do we have a master page with the menu headings up the top (index) or side so people can jump to the section they want? If it's all not on one page, then we need a search function - but how does a search function work for single lines in a table rather than page results?

**Comment by PsychoData** [comment]
Went with a O365 Admin icon, but I turned it the same green as the headers manually. The version up right now is snipped from a screenshot, so it's crappy and has tiny white jaggy edges that bug me 

<img src="https://user-images.githubusercontent.com/3719116/98171810-5a262180-1ebe-11eb-95f6-6d5c06f814fb.png" width="200" height="200">
https://msportals.xyz/images/O365_Admin_Green.png

The Actual icons themselves are part of a Font that MS makes available for free online, so we might be fine licensing-wise, but I haven't actually read [the license](https://static2.sharepointonline.com/files/fabric/assets/microsoft_fabric_assets_license_agreement_nov_2019.pdf) for it 

You can get the whole icon-set here https://aka.ms/WebFluentFonts 
Or download just a subset/browse here 
https://uifabricicons.azurewebsites.net/ 

and you can use an Image Manipulation Program like GIMP to set the color of the "Text" in the font as desired, and save down copies with no background. 

For a while I was chasing to see if there was an SVG Version available for download, so they could scale massively and look perfect, like I found for [Word](https://static2.sharepointonline.com/files/fabric/assets/brand-icons/product/svg/word_48x1.svg), but I wasn't finding any for this icon (or most of them) 

Since I went and made a version out of the font-based version, the file size dropped significantly too (19KB on Snipped to 7KB on font-based, soooo I'll upload that fixed version here in a little bit)
