### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by adamfowlerit** [adamfowlerit/msportals.xyz#35]
Yes, this site doesn't look great on mobile. It's usable, but could be a lot better.

It would be good to at least have auto sizing of the content to the screen size... but open to other ideas.

**Comment by ivandretvic** [comment]
From a UX perspective, id like to see the following:

- list with the URL underneath each item:
![image](https://user-images.githubusercontent.com/6457918/98622269-3733bb80-235d-11eb-9da8-b92a49f4a2f7.png)

- Using Portal Icons where possible (even if they are small) as the brain registers them much faster over text.
- Reducing the space up top so you get more links on the page when it loads
- Reducing the spacing between items

**Comment by ivandretvic** [comment]
With the proposed option of having link underneath, it means that you can have the style sheet display two columns of portals on a desktop (thus more links on page) and a single row for mobile.

I would also change the logo for aka.ms from the emoji to something like this:
![image](https://user-images.githubusercontent.com/6457918/98626163-2dae5180-2365-11eb-9799-6fcd1351b90c.png)

and a small version: 
![image](https://user-images.githubusercontent.com/6457918/98626230-58000f00-2365-11eb-8803-83581d8f08c9.png)

I just mocked them up quickly but can refine easily enough with a transparent background/etc.

**Comment by PsychoData** [comment]
Portal icons like these? https://uifabricicons.azurewebsites.net

**Comment by PsychoData** [comment]
What do you think about something like the app switcher on
portal.office365.com, but that takes you to the admin portal of that
product instead

To be fair some of the products have admin icons like the a with a gear
that we're using for the logo/fave icon, but most products won't have one
directly for admin, which makes me think it might need something more than
just that one icon from that UI fabric icons link I posted above, maybe we
could overlay a settings gear or something?

**Comment by ivandretvic** [comment]
Those icons are a little generic. I would use the logos that the user is familiar with when they usually navigate to that resource. On O365 Admin portal, you can see the icons on the left menu for some of the services. Within Azure are others that are common. For specific services, i would simply put in a transparent spacer image so that alignment is the same, and can replace image in future if needed. I wouldnt expect all links to have a logo, just the main ones. Eg.

- Exchange

**Comment by ivandretvic** [comment]
Also i really nice feature is a Dark mode switch using CSS. Keep the folks happy who dont like dark mode.

**Comment by adamfowlerit** [comment]
You're welcome to get dark mode switch going and submit :) 

I like the logo, can swap it over if you make a transparent one and maybe a tiiiny bit smaller.

The proposed UX change would make the mobile experience better without any effort, but we'd be wasting a lot of screen space. 

If you can grab icons that you want (or start with one) we can try appending that to the start of links where that icon applies to make it a bit visually nicer. I had an idea where we could save a screenshot of each portal's main page for reference too, but unsure about a nice way to implement that without another icon reference to link to it.

**Comment by PsychoData** [comment]
How are the icons generic? These are literally the same icon set that they
make the production icons from in many cases, for example here is Excel
[image: image.png]

and Exchange
[image: image.png]

**Comment by PsychoData** [comment]
Ahh, you probably mean the colorized versions.
Like this excel logo
<data:image/svg+xml;charset=utf-8;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PGRlZnM+PHN0eWxlPi5jbHMtMXtmaWxsOiMyMWEzNjY7fS5jbHMtMntmaWxsOm5vbmU7fS5jbHMtM3tmaWxsOiMxMDdjNDE7fS5jbHMtNHtmaWxsOiMzM2M0ODE7fS5jbHMtNXtmaWxsOiMxODVjMzc7fS5jbHMtNntvcGFjaXR5OjAuNTt9LmNscy03e2ZpbGw6I2ZmZjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkV4Y2VsXzI0eDwvdGl0bGU+PGcgaWQ9IkV4Y2VsIj48ZyBpZD0iXzI0IiBkYXRhLW5hbWU9IjI0Ij48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xNiwxSDdBMSwxLDAsMCwwLDYsMlY3bDEwLDUsNCwxLjVMMjQsMTJWN1oiLz48cmVjdCBjbGFzcz0iY2xzLTIiIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIvPjxyZWN0IGNsYXNzPSJjbHMtMyIgeD0iNiIgeT0iNy4wMiIgd2lkdGg9IjEwIiBoZWlnaHQ9IjQuOTgiLz48cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Ik0yNCwyVjdIMTZWMWg3QTEsMSwwLDAsMSwyNCwyWiIvPjxwYXRoIGNsYXNzPSJjbHMtNSIgZD0iTTE2LDEySDZWMjJhMSwxLDAsMCwwLDEsMUgyM2ExLDEsMCwwLDAsMS0xVjE3WiIvPjxwYXRoIGNsYXNzPSJjbHMtNiIgZD0iTTEzLjgzLDZINlYyMGg3LjZBMS41LDEuNSwwLDAsMCwxNSwxOC42NVY3LjE3QTEuMTgsMS4xOCwwLDAsMCwxMy44Myw2WiIvPjxyZWN0IGlkPSJCYWNrX1BsYXRlIiBkYXRhLW5hbWU9IkJhY2sgUGxhdGUiIGNsYXNzPSJjbHMtMyIgeT0iNSIgd2lkdGg9IjE0IiBoZWlnaHQ9IjE0IiByeD0iMS4xNyIvPjxwYXRoIGNsYXNzPSJjbHMtNyIgZD0iTTMuNDMsMTYsNiwxMiwzLjY0LDhINS41NWwxLjMsMi41NWE0LjYzLDQuNjMsMCwwLDEsLjI0LjU0aDBhNS43Nyw1Ljc3LDAsMCwxLC4yNy0uNTZMOC43Niw4aDEuNzVMOC4wOCwxMmwyLjQ5LDRIOC43MWwtMS41LTIuOEEyLjE0LDIuMTQsMCwwLDEsNywxMi44M0g3YTEuNTQsMS41NCwwLDAsMS0uMTcuMzZMNS4zLDE2WiIvPjxyZWN0IGNsYXNzPSJjbHMtMyIgeD0iMTYiIHk9IjEyIiB3aWR0aD0iOCIgaGVpZ2h0PSI1Ii8+PC9nPjwvZz48L3N2Zz4=>,
but they are not always so easy to find, particularly if they are not in
the App Switcher
[image: image.png]

versus the AdminA listing, which is just based on the Character from the
UIFabricIcons website above
[image: image.png]


I like the overall Look of the "App Switcher" versions better, for the
negative space, but I worry how well they will play on the dark background
of the site - particularly some like the "Admin" A and Gear those white
sections and the A are often clear, Which would look very off
[image: image.png]

The "All Apps" list from the same page has most of the same Apps but with a
"square" motif around them, though some of these won't really have
applicable Logos,
[image: image.png]

**Comment by adamfowlerit** [comment]
Mobile view is much better now and I'd be happy to call it good enough. Having a look into dark/light mode by asking @mdjx :)

**Comment by PsychoData** [comment]
Sounds good to me
