### ISSUE TITLE
Some additional sites that are useful

### ISSUE THREAD

**Issue by ivandretvic** [adamfowlerit/msportals.xyz#37]
https://aka.ms/mfasetup - registering MFA setup
https://myapplications.microsoft.com/#optIn - MyApps page (new one)
https://myaccount.microsoft.com/ - MyAccount (for commercial)
https://account.microsoft.com/ - MyAccount (for consumer)
https://twitter.com/MSFT365Status - Microsoft Twitter status page for MS365

**Comment by adamfowlerit** [comment]
Thanks Ivan!
https://aka.ms/mfasetup - on userportals.md
https://myapplications.microsoft.com/#optIn - on userportals.md
https://myaccount.microsoft.com/ - added to userportals.md
https://account.microsoft.com/ - added to userportals.md
https://twitter.com/MSFT365Status - added to third party portals (not exactly a portal but makes sense)
