### ISSUE TITLE
No GCC links

### ISSUE THREAD

**Issue by jenlg** [adamfowlerit/msportals.xyz#47]
Missing links for GCC areas.  An example would be portal.azure.us.

**Comment by adamfowlerit** [comment]
Trialing using an icon for the GCC links - tested several and couldn't find any more by replacing .com with .us ?

**Comment by adamfowlerit** [comment]
After finding out there's GCC, GCC High and DoD links, I've created a new page, but we need more links!

**Comment by jenlg** [comment]
> After finding out there's GCC, GCC High and DoD links, I've created a new page, but we need more links!

Thank you for this!  If I spot any you are missing, I will report back.
