### ISSUE TITLE
Duplicate Entries on [End User Portals - General]

### ISSUE THREAD

**Issue by kevincallanan** [adamfowlerit/msportals.xyz#49]
My Sign-ins & My Sign-Ins are listed twice (same URL) the only difference is the capitalization in "In"

**Comment by PsychoData** [comment]
Which page is this on?

**Comment by kevincallanan** [comment]
https://msportals.xyz/userportals <- End Users

**Comment by adamfowlerit** [comment]
I see it, removed now. Thank you!
