### ISSUE TITLE
[BUG] Page Build Failure

### ISSUE THREAD

**Issue by adamfowlerit** [adamfowlerit/msportals.xyz#75]
Any updates currently generate this error:

The page build failed for the `master` branch with the following error:

There was a YAML syntax error on line 406 column 30 in `_data/portals/admin.json`: `did not find expected ',' or ']' while parsing a flow sequence`. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-yaml-in-data-file.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=307594809&page_build_id=222839925

**Comment by PsychoData** [comment]
Looks like there were some JSON errors - fixed here https://github.com/adamfowlerit/msportals.xyz/commit/3dc2912a8c1d8723e9f72c63904c6f3f732e6356

Added JSON Validation Workflow/schema here so we can have checks and more detail on why they don't work - https://github.com/adamfowlerit/msportals.xyz/commit/534839758c71a34b0c9aec0c1bbd5b7266602ba7

and it looks like we're building good now!
